language: bash

services:
  - docker

env:
  - VERSION=5.6 VARIANT=cli
  - VERSION=5.6 VARIANT=fpm
  - VERSION=7.0 VARIANT=cli
  - VERSION=7.0 VARIANT=fpm
  - VERSION=7.1 VARIANT=cli
  - VERSION=7.1 VARIANT=fpm

before_script:
  - env | sort
  - cd "$VERSION"
  - image="thomasglachant/docker-php:${VERSION}${VARIANT:+-$VARIANT}"
  - image="${image//'/'/-}"

script:
  - docker build -t ${image} "${VARIANT:-.}"

after_script:
  - docker images