sudo: required

services:
    - docker

matrix:
  include:
    - env: PHP_VERSION="5.6-cli"
    - env: PHP_VERSION="5.6-fpm"
    - env: PHP_VERSION="7-cli"
    - env: PHP_VERSION="7-fpm"

script:
    - bash build-image.sh $PHP_VERSION
