language: bash

services:
  - docker

env:
  - APP=nginx APP_VERSION=1.11
  - APP=php APP_VERSION=5.6 APP_VARIANT=cli
  - APP=php APP_VERSION=5.6 APP_VARIANT=fpm
  - APP=php APP_VERSION=7.0 APP_VARIANT=cli
  - APP=php APP_VERSION=7.0 APP_VARIANT=fpm
  - APP=php APP_VERSION=7.1 APP_VARIANT=cli
  - APP=php APP_VERSION=7.1 APP_VARIANT=fpm

before_script:
  - env | sort
  - DOCKERFILE={APP}{APP_VERSION:+/$APP_VERSION}{APP_VARIANT:+/$APP_VARIANT}
  - IMAGE="thomasglachant/docker:${APP}${APP_VERSION:+$APP_VERSION}${APP_VARIANT:+-$APP_VARIANT}"
  - IMAGE="${IMAGE//'/'/-}"

script:
  - docker build -t ${IMAGE} "$DOCKERFILE"

after_script:
  - docker images

after_success:
  - >
    [ "$TRAVIS_BRANCH" == "master" ]
    && curl -X POST -H "Content-Type: application/json"
    --data '{"build": true}'
    https://registry.hub.docker.com/u/thomasglachant/docker-php/trigger/${DOCKERHUB_TOKEN}/