language: bash

services:
  - docker

env:
  - PHP_VERSION=5.6 VARIANT=cli
  - PHP_VERSION=5.6 VARIANT=fpm
  - PHP_VERSION=7.0 VARIANT=cli
  - PHP_VERSION=7.0 VARIANT=fpm
  - PHP_VERSION=7.1 VARIANT=cli
  - PHP_VERSION=7.1 VARIANT=fpm

before_script:
  - env | sort
  - cd "$PHP_VERSION"
  - image="thomasglachant/docker-php:${PHP_VERSION}${VARIANT:+-$VARIANT}"
  - image="${image//'/'/-}"

script:
  - echo "OK"
  #- docker build -t ${image} "${VARIANT:-.}"

after_script:
  - docker images

notifications:
  after_success:
    - >
      [ "$TRAVIS_BRANCH" == "master" ]
      && curl -X POST -H "Content-Type: application/json"
      --data '{"build": true}'
      https://registry.hub.docker.com/u/thomasglachant/docker-php/trigger/${DOCKERHUB_TOKEN}/